import SiblingShared

open OrbitSynthesis.StrongSignedRouter.FormalOptimized

#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.Rails.comp_assoc
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.composeRailTerms_correct
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.digitRailTerms_correct
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.finalRailPairTerms_match_frozen_program
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.trailing_noRight_gain_reuse
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.totalRailNodes_le_three_mul_pow
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.totalRailNodes_scaled_sharp
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.optimized_materialization_bounds
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.oneRail_trailing_zero_one_suffix
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.sibling_notZero_middle_eq_one_right
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.siblingSharedNodes_scaled_envelope
#print axioms OrbitSynthesis.StrongSignedRouter.FormalOptimized.three_mul_siblingSharedNodes_le_seven_mul_pow
