"""Exact small-carrier structure for parameter cores of pure discriminator algebras.

For a finite carrier ``A`` and arity greater than one, a table is polynomial
with named constants ``C`` exactly when:

* every output lies in ``C`` or already occurs among the arguments; and
* the table commutes with every carrier permutation fixing ``C`` pointwise.

The point-stabilizer is generated by transpositions outside ``C``, so the
membership oracle below is exact without enumerating the full symmetric group.
The mathematical proof and scope boundaries live in
``notes/DISCRIMINATOR_CORE_INTERSECTION_LAW.md``.
"""
from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, product
from typing import Callable, Hashable, Mapping, Sequence

Value = Hashable
Row = tuple[Value, ...]
TableLike = Mapping[Row, Value] | Callable[..., Value]


@dataclass(frozen=True)
class CoverIntersectionProfile:
    """The block data retained by an incomparable full-cover core pair."""

    meet: frozenset[Value]
    left_only: frozenset[Value]
    right_only: frozenset[Value]

    @property
    def binary_operation_count(self) -> int:
        """Exact number of binary operations in the two clone intersection.

        For ``e=|meet|``, ``x=|left_only|`` and ``y=|right_only|``, the
        intersection is the orbit-seed product for
        ``Sym(left_only) x Sym(right_only)`` with seed set
        ``meet union range(row)``.  Incomparable cover pairs have ``x,y>0``.
        """

        e = len(self.meet)
        x = len(self.left_only)
        y = len(self.right_only)
        if x == 0 or y == 0:
            raise ValueError("profile is not an incomparable cover")
        fixed_named_rows = e * e
        one_fresh_orbits = 4 * e + 2
        two_fresh_orbits = 2 + int(x >= 2) + int(y >= 2)
        return (
            (e ** fixed_named_rows)
            * ((e + 1) ** one_fresh_orbits)
            * ((e + 2) ** two_fresh_orbits)
        )


def _carrier_tuple(carrier: Sequence[Value]) -> tuple[Value, ...]:
    values = tuple(carrier)
    if len(set(values)) != len(values):
        raise ValueError("carrier values must be distinct")
    if not values:
        raise ValueError("carrier must be nonempty")
    return values


def _value_at(table: TableLike, row: Row) -> Value:
    if isinstance(table, Mapping):
        try:
            return table[row]
        except KeyError as error:
            raise ValueError(f"table omits row {row!r}") from error
    return table(*row)


def _swap(value: Value, left: Value, right: Value) -> Value:
    if value == left:
        return right
    if value == right:
        return left
    return value


def is_parameter_polynomial_table(
    carrier: Sequence[Value],
    core: Sequence[Value] | frozenset[Value],
    arity: int,
    table: TableLike,
) -> bool:
    """Exact membership in the ``core``-polynomial clone of a pure discriminator.

    The characterization used here is scoped to arity greater than one.  It is
    an exact finite oracle, not an inference that an arbitrary supplied algebra
    has discriminator structure.
    """

    values = _carrier_tuple(carrier)
    carrier_set = frozenset(values)
    fixed = frozenset(core)
    if not fixed <= carrier_set:
        raise ValueError("core contains a value outside the carrier")
    if arity <= 1:
        raise ValueError("the exact characterization is scoped to arity > 1")

    rows = tuple(product(values, repeat=arity))
    cached: dict[Row, Value] = {}
    for row in rows:
        output = _value_at(table, row)
        if output not in carrier_set:
            return False
        if output not in fixed and output not in row:
            return False
        cached[row] = output

    movable = tuple(value for value in values if value not in fixed)
    for left, right in combinations(movable, 2):
        for row in rows:
            mapped_row = tuple(_swap(value, left, right) for value in row)
            if cached[mapped_row] != _swap(cached[row], left, right):
                return False
    return True


def core_intersection_collapses(
    carrier: Sequence[Value],
    left: Sequence[Value] | frozenset[Value],
    right: Sequence[Value] | frozenset[Value],
) -> bool:
    """Whether ``Pol_left ∩ Pol_right`` equals ``Pol_(left ∩ right)``.

    For pure finite discriminator algebras and every arity greater than one,
    collapse holds exactly unless ``left`` and ``right`` are incomparable and
    jointly cover the whole carrier.
    """

    values = frozenset(_carrier_tuple(carrier))
    c = frozenset(left)
    d = frozenset(right)
    if not c <= values or not d <= values:
        raise ValueError("core outside carrier")
    return c <= d or d <= c or (c | d) != values


def incomparable_cover_profile(
    carrier: Sequence[Value],
    left: Sequence[Value] | frozenset[Value],
    right: Sequence[Value] | frozenset[Value],
) -> CoverIntersectionProfile:
    values = frozenset(_carrier_tuple(carrier))
    c = frozenset(left)
    d = frozenset(right)
    if not c <= values or not d <= values:
        raise ValueError("core outside carrier")
    if c <= d or d <= c or (c | d) != values:
        raise ValueError("cores must be incomparable and cover the carrier")
    return CoverIntersectionProfile(
        meet=c & d,
        left_only=c - d,
        right_only=d - c,
    )


def cover_intersection_witness(
    carrier: Sequence[Value],
    left: Sequence[Value] | frozenset[Value],
    right: Sequence[Value] | frozenset[Value],
    arity: int = 2,
) -> dict[Row, Value]:
    """Construct a table in both cover-core clones but not their meet clone."""

    values = _carrier_tuple(carrier)
    profile = incomparable_cover_profile(values, left, right)
    if arity <= 1:
        raise ValueError("witness requires arity > 1")
    left_only = profile.left_only
    table: dict[Row, Value] = {}
    for row in product(values, repeat=arity):
        table[row] = row[0] if row[0] in left_only else row[1]
    return table


def minimal_core_family_has_cover_property(
    carrier: Sequence[Value],
    family: Sequence[Sequence[Value] | frozenset[Value]],
) -> bool:
    """Check the necessary pairwise-cover condition for distinct minimal cores."""

    values = frozenset(_carrier_tuple(carrier))
    cores = tuple(frozenset(core) for core in family)
    if any(not core <= values for core in cores):
        raise ValueError("core outside carrier")
    if len(set(cores)) != len(cores):
        return False
    return all(left | right == values for left, right in combinations(cores, 2))


def complement_blocks(
    carrier: Sequence[Value],
    family: Sequence[Sequence[Value] | frozenset[Value]],
) -> tuple[frozenset[Value], ...]:
    """Return complements, rejecting a family that violates pairwise cover."""

    values = frozenset(_carrier_tuple(carrier))
    cores = tuple(frozenset(core) for core in family)
    if not minimal_core_family_has_cover_property(tuple(values), cores):
        raise ValueError("family does not satisfy the pairwise-cover condition")
    return tuple(values - core for core in cores)
