"""Finite universal-algebra utilities for the standalone OrbitSynthesis kernel.

No Tau dependency.

The first implementation intentionally targets small finite carriers.  It can
discover subalgebras, automorphisms, and internal isomorphisms exhaustively.
Those routines are exact but factorial/exponential and should later be replaced
or supplemented by specialized group/CSP algorithms for larger carriers.
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import combinations, permutations, product
from typing import Hashable, Iterable, Mapping, Sequence

Value = Hashable


@dataclass(frozen=True)
class FiniteOperation:
    """A total finitary operation represented by its complete table."""

    name: str
    arity: int
    table_items: tuple[tuple[tuple[Value, ...], Value], ...]

    @classmethod
    def from_mapping(
        cls,
        name: str,
        arity: int,
        table: Mapping[tuple[Value, ...], Value],
    ) -> "FiniteOperation":
        return cls(name=name, arity=arity, table_items=tuple(table.items()))

    @property
    def table(self) -> dict[tuple[Value, ...], Value]:
        return dict(self.table_items)

    def __call__(self, *args: Value) -> Value:
        if len(args) != self.arity:
            raise ValueError(
                f"{self.name} expects arity {self.arity}, got {len(args)}"
            )
        return self.table[tuple(args)]


@dataclass(frozen=True)
class InternalIsomorphism:
    """An isomorphism between two subalgebras of one finite algebra."""

    domain: frozenset[Value]
    codomain: frozenset[Value]
    mapping_items: tuple[tuple[Value, Value], ...]

    @property
    def mapping(self) -> dict[Value, Value]:
        return dict(self.mapping_items)

    def applies_to(self, values: Sequence[Value]) -> bool:
        return all(value in self.domain for value in values)

    def map_value(self, value: Value) -> Value:
        return self.mapping[value]

    def map_tuple(self, values: Sequence[Value]) -> tuple[Value, ...]:
        mapping = self.mapping
        return tuple(mapping[value] for value in values)


@dataclass
class FiniteAlgebra:
    """A small finite algebra given by explicit operation tables."""

    values: tuple[Value, ...]
    operations: tuple[FiniteOperation, ...]

    def __post_init__(self) -> None:
        if not self.values:
            raise ValueError("finite algebra carrier must be nonempty")
        if len(set(self.values)) != len(self.values):
            raise ValueError("carrier values must be distinct")
        carrier = set(self.values)
        for operation in self.operations:
            expected = set(product(self.values, repeat=operation.arity))
            actual = {args for args, _ in operation.table_items}
            if actual != expected:
                missing = expected - actual
                extra = actual - expected
                raise ValueError(
                    f"operation {operation.name!r} is not a complete table; "
                    f"missing={len(missing)}, extra={len(extra)}"
                )
            if any(result not in carrier for _, result in operation.table_items):
                raise ValueError(
                    f"operation {operation.name!r} leaves the carrier"
                )

    @classmethod
    def from_callables(
        cls,
        values: Sequence[Value],
        operations: Mapping[str, tuple[int, object]],
    ) -> "FiniteAlgebra":
        """Convenience constructor for tests/examples.

        ``operations`` maps a name to ``(arity, callable)``.  The callable is
        evaluated exhaustively and converted into an immutable operation table.
        """

        carrier = tuple(values)
        built: list[FiniteOperation] = []
        for name, (arity, function) in operations.items():
            table = {
                args: function(*args)  # type: ignore[misc]
                for args in product(carrier, repeat=arity)
            }
            built.append(FiniteOperation.from_mapping(name, arity, table))
        return cls(values=carrier, operations=tuple(built))

    def generated_subalgebra(self, generators: Iterable[Value]) -> frozenset[Value]:
        """Return the subalgebra generated by ``generators``.

        The current synthesis kernel assumes at least one observed state value,
        so the empty-generated-subalgebra convention is deliberately not
        invented here.  If no generator is supplied, callers must provide the
        appropriate nullary-constant semantics explicitly in a later extension.
        """

        generated = set(generators)
        if not generated:
            raise ValueError("generated_subalgebra requires at least one generator")
        if not generated <= set(self.values):
            raise ValueError("generator outside carrier")

        changed = True
        while changed:
            changed = False
            current = tuple(generated)
            for operation in self.operations:
                for args in product(current, repeat=operation.arity):
                    result = operation(*args)
                    if result not in generated:
                        generated.add(result)
                        changed = True
        return frozenset(generated)

    def is_subalgebra(self, subset: Iterable[Value]) -> bool:
        values = frozenset(subset)
        if not values:
            return False
        if not values <= set(self.values):
            return False
        current = tuple(values)
        for operation in self.operations:
            for args in product(current, repeat=operation.arity):
                if operation(*args) not in values:
                    return False
        return True

    def subalgebras(self) -> tuple[frozenset[Value], ...]:
        """Enumerate all nonempty subalgebras exactly."""

        result: list[frozenset[Value]] = []
        for size in range(1, len(self.values) + 1):
            for chosen in combinations(self.values, size):
                subset = frozenset(chosen)
                if self.is_subalgebra(subset):
                    result.append(subset)
        return tuple(result)

    def _is_isomorphism_mapping(
        self,
        domain: frozenset[Value],
        codomain: frozenset[Value],
        mapping: Mapping[Value, Value],
    ) -> bool:
        if set(mapping) != set(domain):
            return False
        if set(mapping.values()) != set(codomain):
            return False
        if len(set(mapping.values())) != len(mapping):
            return False

        source = tuple(domain)
        for operation in self.operations:
            for args in product(source, repeat=operation.arity):
                lhs = mapping[operation(*args)]
                rhs = operation(*(mapping[arg] for arg in args))
                if lhs != rhs:
                    return False
        return True

    def internal_isomorphisms(self) -> tuple[InternalIsomorphism, ...]:
        """Enumerate every isomorphism between nonempty subalgebras.

        This includes identity maps, automorphisms of proper subalgebras, and
        isomorphisms between distinct subalgebras.
        """

        subalgebras = self.subalgebras()
        result: list[InternalIsomorphism] = []
        for domain in subalgebras:
            source = tuple(domain)
            for codomain in subalgebras:
                if len(domain) != len(codomain):
                    continue
                target = tuple(codomain)
                for permuted in permutations(target):
                    mapping = dict(zip(source, permuted))
                    if self._is_isomorphism_mapping(domain, codomain, mapping):
                        result.append(
                            InternalIsomorphism(
                                domain=domain,
                                codomain=codomain,
                                mapping_items=tuple(mapping.items()),
                            )
                        )
        return tuple(result)

    def automorphisms(self) -> tuple[InternalIsomorphism, ...]:
        carrier = frozenset(self.values)
        return tuple(
            iso
            for iso in self.internal_isomorphisms()
            if iso.domain == carrier and iso.codomain == carrier
        )
