"""Definable-constant closure and exact generator-rank catalogues."""

from __future__ import annotations

from collections.abc import Hashable, Iterable, Sequence
from dataclasses import dataclass
from itertools import combinations, product
from typing import Any

Value = Hashable
Observation = tuple[Value, ...]


@dataclass(frozen=True)
class ParameterCoreInfo:
    """One closed definable-constant core and its minimum raw generators."""

    core: frozenset[Value]
    rank: int
    witnesses: tuple[frozenset[Value], ...]


def _carrier_index(values: Sequence[Value]) -> dict[Value, int]:
    return {value: index for index, value in enumerate(values)}


def _set_order_key(
    values: Iterable[Value], carrier: Sequence[Value]
) -> tuple[int, ...]:
    chosen = frozenset(values)
    return tuple(index for index, value in enumerate(carrier) if value in chosen)


def closure_with_parameters(
    algebra: Any, generators: Iterable[Value]
) -> frozenset[Value]:
    """Return the subuniverse generated by ``generators`` and nullary values.

    Unlike ``FiniteAlgebra.generated_subalgebra``, this operation intentionally
    supports an empty seed.  Nullary basic operations are included
    automatically.  If the signature has no nullary operations and no seed is
    supplied, the exact result is the empty definable-constant core.
    """

    carrier = tuple(algebra.values)
    carrier_set = set(carrier)
    generated = set(generators)
    if not generated <= carrier_set:
        raise ValueError("parameter or generator outside carrier")

    changed = True
    while changed:
        changed = False
        current = tuple(generated)
        for operation in algebra.operations:
            arity = int(operation.arity)
            if arity == 0:
                argument_rows = ((),)
            elif not current:
                argument_rows = ()
            else:
                argument_rows = product(current, repeat=arity)
            for args in argument_rows:
                result = operation(*args)
                if result not in carrier_set:
                    raise ValueError(
                        f"operation {getattr(operation, 'name', '<operation>')!r} "
                        "leaves the carrier"
                    )
                if result not in generated:
                    generated.add(result)
                    changed = True
    return frozenset(generated)


def parameter_core(algebra: Any, parameters: Iterable[Value] = ()) -> frozenset[Value]:
    """The exact definable-constant closure of a raw parameter set."""

    return closure_with_parameters(algebra, parameters)


def parameter_core_catalog(algebra: Any) -> tuple[ParameterCoreInfo, ...]:
    """Enumerate distinct cores with exact generator rank and all min witnesses.

    This is exponential in the carrier size and serves as a small-carrier exact
    oracle.  The carrier's declared order makes the result deterministic.
    """

    carrier = tuple(algebra.values)
    best: dict[frozenset[Value], tuple[int, list[frozenset[Value]]]] = {}
    for size in range(len(carrier) + 1):
        for chosen_tuple in combinations(carrier, size):
            chosen = frozenset(chosen_tuple)
            core = parameter_core(algebra, chosen)
            old = best.get(core)
            if old is None or size < old[0]:
                best[core] = (size, [chosen])
            elif size == old[0]:
                old[1].append(chosen)

    infos = [
        ParameterCoreInfo(
            core=core,
            rank=rank,
            witnesses=tuple(
                sorted(
                    witnesses,
                    key=lambda witness: _set_order_key(witness, carrier),
                )
            ),
        )
        for core, (rank, witnesses) in best.items()
    ]
    infos.sort(
        key=lambda info: (
            info.rank,
            len(info.core),
            _set_order_key(info.core, carrier),
        )
    )
    return tuple(infos)


def eligible_core_isomorphisms(
    algebra: Any,
    core: Iterable[Value],
    *,
    internal_isomorphisms: Sequence[Any] | None = None,
) -> tuple[Any, ...]:
    """Internal isomorphisms of the expansion naming ``core`` pointwise."""

    fixed = frozenset(core)
    if parameter_core(algebra, fixed) != fixed:
        raise ValueError("core must be closed under definable constants")
    all_isos = tuple(
        internal_isomorphisms
        if internal_isomorphisms is not None
        else algebra.internal_isomorphisms()
    )
    out = []
    for isomorphism in all_isos:
        if not fixed <= isomorphism.domain:
            continue
        if not fixed <= isomorphism.codomain:
            continue
        mapping = isomorphism.mapping
        if any(mapping.get(value) != value for value in fixed):
            continue
        out.append(isomorphism)
    return tuple(out)


def generated_at_observation(
    algebra: Any,
    core: Iterable[Value],
    observation: Sequence[Value],
) -> frozenset[Value]:
    return closure_with_parameters(algebra, tuple(core) + tuple(observation))
